spring:
  main:
    banner-mode: off
logging:
  level:
    root: off

application:
  tickets:
    source-file:
      name: tickets
      type: json
      path: ${application.tickets.source-file.name}.${application.tickets.source-file.type}
